### ISSUE TITLE
Issue building parcel

### ISSUE THREAD

**Issue by adamonduty** [prateek/nifi-parcel#1] opened 2015-10-15 04:14 UTC
Thanks for this project!

I followed the instructions, but ran into an issue while trying to build:

```
POINT_VERSION=5 VALIDATOR_DIR=/tmp/cm_ext ./build-parcel.sh /tmp/nifi/nifi-assembly/target/nifi-*-SNAPSHOT-bin.tar.gz
nifi-0.3.1-SNAPSHOT/README
nifi-0.3.1-SNAPSHOT/LICENSE
nifi-0.3.1-SNAPSHOT/NOTICE
...
sed: can't read s/<VERSION-FULL>/0.0.5.nifi.p0.5/g: No such file or directory
```

This is on Centos 6.7.  Any suggestions?

**Comment by prateek** [comment] 2015-10-15 06:35
Thanks for reporting the issue! 

I'm pretty sure the cause for the bug is the difference between [OSX sed and Linux sed](http://stackoverflow.com/questions/2320564/variations-of-sed-between-osx-and-gnu-linux). It's throwing up on these [lines](https://github.com/prateek/nifi-parcel/blob/master/build-parcel.sh#L48-L49). 

Could you try replacing 

``` sh
  sed -i "" "s/<VERSION-FULL>/$FULL_VERSION/g"     $file
  sed -i "" "s/<VERSION-SHORT>/${SHORT_VERSION}/g" $file 
```

with 

``` sh
  sed -i -e "s/<VERSION-FULL>/$FULL_VERSION/g"     $file
  sed -i -e "s/<VERSION-SHORT>/${SHORT_VERSION}/g" $file 
```

See if that does the trick?

**Comment by adamonduty** [comment] 2015-10-16 04:40
Ah, that helps! 

Next issue:

```
Found parcel NIFI-0.0.5.nifi.p0.5-el6.parcel
Traceback (most recent call last):
  File "/tmp/cm_ext/make_manifest/make_manifest.py", line 114, in <module>
    manifest = make_manifest(path)
  File "/tmp/cm_ext/make_manifest/make_manifest.py", line 79, in make_manifest
    with tarfile.open(fullpath, 'r') as tar:
AttributeError: 'TarFile' object has no attribute '__exit__'
```

Should I file an issue with `cm_ext`?

**Comment by prateek** [comment] 2015-10-17 01:11
Looks like an issue with Python 2.6, found another reference to the bug [here](https://github.com/mgedmin/check-manifest/issues/22). 

I'm happy to keep helping you debug if you want to go down that route. In case you only want to play with the parcel, I uploaded a build to S3 - [download](http://prateek-public-files.s3.amazonaws.com/nifi-build.tar)

**Comment by minghaod** [comment] 2015-12-07 04:59
Hi, thanks for this project.

After the activation of NIFI parcel in Cloudera Manager, zookeeper and every service depends on it can no longer be started, all services has same Configuration Warning appear on the right of their name:
Mismatched CDH versions: host has NONE but role expects 5.
While deactivating this parcel allows all services working normally. So I'm wondering if it results from some potential errors in this parcel or something in my own machine.

Thanks.

**Comment by david-w-webb** [comment] 2016-05-25 14:31
Hi, I found a few issues with the instructions, a few notes, and am currently in an issue with building the parcel.

The instructions specify http://github.com/... on a few lines.  I found that https://github.com/... was necessary to clone the project.

Notes:
The nifi build requires java and javac 8 and maven 3.1 (I think) and up.  It also requires npm and bower.  

My issue - I'm not sure how to proceed.  When running mvn as root, I get errors that bower doesn't want to run under sudo.  When running mvn with my userid, I get the following errors.  I manually installed npm and bower, but they didn't resolve the errors:

`[INFO] --- frontend-maven-plugin:1.0:npm (install-bower) @ nifi-web-ui ---
[INFO] Running 'npm install bower' in /tmp/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/target/frontend-working-directory
[ERROR] npm http GET https://registry.npmjs.org/bower
[ERROR] npm http 304 https://registry.npmjs.org/bower
[INFO] bower@1.7.9 ../../node_modules/bower
[INFO]
[INFO] --- frontend-maven-plugin:1.0:bower (bower-install) @ nifi-web-ui ---
[INFO] Running 'bower install --config.directory=/tmp/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/target/nifi-web-ui-1.0.0-SNAPSHOT/assets' in /tmp/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/target/frontend-working-directory
[ERROR]
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '/tmp/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/target/frontend-working-directory/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:901:3
`

**Comment by prateek** [comment] 2016-09-18 01:33
@minghaod @david-w-webb are you guys still stuck on these issues (he says casually, a year later...)?

**Comment by david-w-webb** [comment] 2016-09-25 03:09
We gave up on Nifi since we are a Cloudera shop and they recommend StreamSets instead.  I didn't determine how t create my own parcels.

```
  From: Prateek Rungta <notifications@github.com>
```

 To: prateek/nifi-parcel nifi-parcel@noreply.github.com 
Cc: david-w-webb david-w-webb@sbcglobal.net; Mention mention@noreply.github.com
 Sent: Saturday, September 17, 2016 9:33 PM
 Subject: Re: [prateek/nifi-parcel] Issue building parcel (#1)

@minghaod @david-w-webb are you guys still stuck on these issues (he says casually, a year later...)? —

**Comment by prateek** [comment] 2016-09-26 04:06
Cool, I hope that goes great! 

FYI if you want to write a parcel at some point, it's simple and the docs are pretty good: https://github.com/cloudera/cm_ext/wiki/Building-a-parcel 

Closing for now.

**Closed as completed by prateek** 2016-09-26 04:06 UTC

**Comment by pacosoplas** [comment] 2018-03-23 21:43
After install everything correcly, from cloudera i have this message from parcels page, my OS is ubuntu on my cluster

Error del parcel NIFI-0.0.5.nifi.p0.5-trusty : Parcel no disponible para la distribución del SO UBUNTU_TRUSTY.

**Comment by imayanksrivastava** [comment] 2018-07-21 22:04
Hi 

I have been trying to install nifi from the source. But fail to. How do i solve this issue. 

[ERROR] Failed to execute goal on project nifi-livy-processors: Could not resolve dependencies for project org.apache.nifi:nifi-livy-processors:jar:1.8.0-SNAPSHOT: Could not find artifact org.apache.nifi:nifi-standard-processors:jar:tests:1.8.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nifi-livy-processors
Destroying 1 processes
Destroying process..
Destroyed 1 processes
